person:
  lastName: zhangsan
  age: 20
  boss: false
  birth: 2018/08/08
  maps: {k1: v1, k2: 18}
  lists:
    - wocao
    - caodan
    - rinimei
  dog:
    name: 二哈
    age: 1

# 激活dev配置文件
spring:
  profiles:
    active: dev

# 多环境文档块配置
---
# 开发环境配置
spring:
  profiles: dev
server:
  port: 8081
---
# 测试环境配置
spring:
  profiles: test
server:
  port: 8082
---
# 生产环境配置
spring:
  profiles: prod
server:
  port: 8083
