person:
  lastName: zhangsan
  age: 20
  boss: false
  birth: 2018/08/08
  maps: {k1: v1, k2: 18}
  lists:
    - wocao
    - caodan
    - rinimei
  dog:
    name: 二哈
    age: 1

# 打印加载了哪些配置没有加载哪些配置
# debug: false

# 指定log4j2的配置文件, 默认会从项目根目录找名叫log4j2-spring1.xml的配置文件
logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace

# 激活dev配置文件
spring:
  profiles:
    active: dev
  # JDBC数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.58.128:3306/ssm?serverTimezone=UTC
    # url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 多环境文档块配置
---
# 开发环境配置
spring:
  profiles: dev
server:
  port: 8081
---
# 测试环境配置
spring:
  profiles: test
server:
  port: 8082
---
# 生产环境配置
spring:
  profiles: prod
server:
  port: 8083
